version: '3.7'

services:
  webservice:
    image: nginx:1.21-alpine
    container_name: ${APP_NAME}_${APP_ENV}_webservice
    restart: on-failure
    depends_on:
      - app
    ports:
      - "${DOCKER_WEBSERVICE_PORT-80}:80"
      - "${DOCKER_WEBSERVICE_SSL_PORT-443}:443"
    volumes:
      - ./:/app
      - ./storage:/app/storage
      - ./storage/app/public/media:/app/public/media
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    image: github
    container_name: ${APP_NAME}_${APP_ENV}_app
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php-fpm/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    command: php-fpm

  db:
    image: postgres:13.2-alpine
    container_name: ${APP_NAME}_${APP_ENV}_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - '${DOCKER_DATA_PATH-/var/data}/db:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  redis:
    image: 'redis:alpine'
    container_name: ${APP_NAME}_${APP_ENV}_redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - '${DOCKER_DATA_PATH-/var/data}/redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  composer:
    image: composer:latest
    container_name: ${APP_NAME}_${APP_ENV}_composer
    working_dir: /app
    restart: "no"
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - ./:/app/
      - ${HOME}/.composer:/tmp
      - /run/user/1000/keyring/ssh:/ssh-auth.sock
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

